### ISSUE TITLE
Re-add shrinkpack once we figure out what is going on with it

### ISSUE THREAD

**Issue by aramonc** [cuemby/hapi-bootstrap#4]
Right now shrinkpack fails with some of our dependencies. See [open issue](https://github.com/JamieMason/shrinkpack/issues/78). Having shrinkpack work would be great as it helps the Cuba team not have to download dependencies every time. They just need to clone the repo.

**Comment by JamieMason** [comment]
Hey @aramonc, `npm` had a [regression affecting shrinkwrap](https://github.com/npm/npm/pull/13214) in versions 3.8.8 to 3.10.3. 

If you could try installing `npm` 3.10.4 or newer (or 3.8.7 or older) – you should be able to install shrinkpacked projects without a problem.

Hope this helps, thanks.

Jamie

**Comment by aramonc** [comment]
Updating NPM to the latest seemed to work. So I'll add shrinkpack back to the Pull Request. @ar4mirez we need to add the README with instructions to update to the latest NPM. We'll have to figure out how to get the Cuba team to install the right versions of the platform.
